// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'dart:io';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return FirebaseOptions(
        apiKey: 'AIzaSyAg_GdWl8H4YPCYf_YVU4_QLCzgwKQsvQ0',
        appId: '1:382353492886:web:0244edc8e7dd11710b2bb7',
        messagingSenderId: '382353492886',
        projectId: 'newproject-b2c20',
        authDomain: 'newproject-b2c20.firebaseapp.com',
        storageBucket: 'newproject-b2c20.firebasestorage.app',
        databaseURL: 'https://newproject-b2c20-default-rtdb.firebaseio.com/'
      );
    } else if (Platform.isAndroid) {
      return FirebaseOptions(
        apiKey: 'AIzaSyCriT93yH5Z0j5quoMtWCNFDHoEfUICDvk',
        appId: '1:382353492886:android:d18f36f00da8cbed0b2bb7',
        messagingSenderId: '382353492886',
        projectId: 'newproject-b2c20',
        storageBucket: 'newproject-b2c20.firebasestorage.app',
        databaseURL: 'https://newproject-b2c20-default-rtdb.firebaseio.com/'
      );
    }  else {
      throw UnsupportedError('Unsupported platform');
    }
  }
}
